name: base_api
description: A wrapper for base api implementation.
version: 1.0.0+1
homepage: null

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  coverage: ^1.0.3
  mocktail: ^0.2.0
  test: ^1.16.4
