name: google_books_api
description: A Dart API Client for the Google Books API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  base_api:
    path: ../base_api

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.3
  freezed: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.2.0
  test: ^1.20.1
