name: chingu_bookfinder_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  firebase_authentication:
    path: ./packages/firebase_authentication
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  go_router: ^4.1.0
  google_books_api:
    path: ./packages/google_books_api
  html: ^0.15.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  network_image_mock: ^2.1.1
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
