// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0j2lz0VL9tWh8LUE1ugnPjej6785Af0',
    appId: '1:546355457454:android:9e4653055985d6fe302c3f',
    messagingSenderId: '546355457454',
    projectId: 'chingu-bookfinder-flutter',
    storageBucket: 'chingu-bookfinder-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gt4q_pVC5kGcid4cMmdCoCCgKq--lvE',
    appId: '1:546355457454:ios:48d515e0ea4f7bba302c3f',
    messagingSenderId: '546355457454',
    projectId: 'chingu-bookfinder-flutter',
    storageBucket: 'chingu-bookfinder-flutter.appspot.com',
    androidClientId:
        '546355457454-kdu9ik159vm0eitfgm9fsidou0ja1u0r.apps.googleusercontent.com',
    iosClientId:
        '546355457454-f00t6a41ogoqksb6o5159bjbmonv17nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.chingu-bookfinder-flutter',
  );
}
