name: firebase_api
description: Firebase Api
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.0

dev_dependencies:
  coverage: ^1.0.3
  firebase_auth_platform_interface: ^6.3.2
  firebase_core_platform_interface: ^4.4.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

dependency_overrides:
  firebase_core_platform_interface: 4.4.1
