name: book_repository
description: A Dart Repository which manages the books domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  base_api:
    path: ../base_api
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  google_books_api:
    path: ../google_books_api

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.3
  json_serializable: ^6.1.5
  mocktail: ^0.2.0
  test: ^1.20.1
